/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const ContentItem = IDL.Record({
  'id' : IDL.Text,
  'uploaderPid' : IDL.Principal,
  'title' : IDL.Text,
  'contentType' : IDL.Variant({ 'audio' : IDL.Null, 'story' : IDL.Null }),
  'thumbnailBlobId' : IDL.Opt(ExternalBlob),
  'createdAt' : Time,
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'blobId' : IDL.Opt(ExternalBlob),
  'textContent' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat32,
  'userName' : IDL.Text,
  'contentId' : IDL.Text,
  'text' : IDL.Text,
  'userPid' : IDL.Principal,
  'timestamp' : Time,
});
export const Progress = IDL.Record({
  'contentId' : IDL.Text,
  'lastAccessed' : Time,
  'position' : IDL.Nat32,
});
export const ContentItemWithLikes = IDL.Record({
  'id' : IDL.Text,
  'uploaderPid' : IDL.Principal,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat32,
  'contentType' : IDL.Variant({ 'audio' : IDL.Null, 'story' : IDL.Null }),
  'thumbnailBlobId' : IDL.Opt(ExternalBlob),
  'createdAt' : Time,
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'blobId' : IDL.Opt(ExternalBlob),
  'textContent' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkContent' : IDL.Func([IDL.Text], [], []),
  'getAllContent' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForContent' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getContentByType' : IDL.Func(
      [IDL.Variant({ 'audio' : IDL.Null, 'story' : IDL.Null })],
      [IDL.Vec(ContentItem)],
      ['query'],
    ),
  'getLikeCount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat32)], ['query']),
  'getProgress' : IDL.Func([IDL.Text], [IDL.Opt(Progress)], ['query']),
  'getRecentUploads' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
  'getTrendingContent' : IDL.Func(
      [],
      [IDL.Vec(ContentItemWithLikes)],
      ['query'],
    ),
  'getUserBookmarks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeContent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProgress' : IDL.Func([IDL.Text, IDL.Nat32], [], []),
  'searchContentByTitle' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContentItem)],
      ['query'],
    ),
  'unbookmarkContent' : IDL.Func([IDL.Text], [], []),
  'unlikeContent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'uploadContent' : IDL.Func([ContentItem], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const ContentItem = IDL.Record({
    'id' : IDL.Text,
    'uploaderPid' : IDL.Principal,
    'title' : IDL.Text,
    'contentType' : IDL.Variant({ 'audio' : IDL.Null, 'story' : IDL.Null }),
    'thumbnailBlobId' : IDL.Opt(ExternalBlob),
    'createdAt' : Time,
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'blobId' : IDL.Opt(ExternalBlob),
    'textContent' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat32,
    'userName' : IDL.Text,
    'contentId' : IDL.Text,
    'text' : IDL.Text,
    'userPid' : IDL.Principal,
    'timestamp' : Time,
  });
  const Progress = IDL.Record({
    'contentId' : IDL.Text,
    'lastAccessed' : Time,
    'position' : IDL.Nat32,
  });
  const ContentItemWithLikes = IDL.Record({
    'id' : IDL.Text,
    'uploaderPid' : IDL.Principal,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat32,
    'contentType' : IDL.Variant({ 'audio' : IDL.Null, 'story' : IDL.Null }),
    'thumbnailBlobId' : IDL.Opt(ExternalBlob),
    'createdAt' : Time,
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'blobId' : IDL.Opt(ExternalBlob),
    'textContent' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkContent' : IDL.Func([IDL.Text], [], []),
    'getAllContent' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForContent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getContentByType' : IDL.Func(
        [IDL.Variant({ 'audio' : IDL.Null, 'story' : IDL.Null })],
        [IDL.Vec(ContentItem)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat32)], ['query']),
    'getProgress' : IDL.Func([IDL.Text], [IDL.Opt(Progress)], ['query']),
    'getRecentUploads' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
    'getTrendingContent' : IDL.Func(
        [],
        [IDL.Vec(ContentItemWithLikes)],
        ['query'],
      ),
    'getUserBookmarks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeContent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProgress' : IDL.Func([IDL.Text, IDL.Nat32], [], []),
    'searchContentByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContentItem)],
        ['query'],
      ),
    'unbookmarkContent' : IDL.Func([IDL.Text], [], []),
    'unlikeContent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'uploadContent' : IDL.Func([ContentItem], [], []),
  });
};

export const init = ({ IDL }) => { return []; };