/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : number,
  'userName' : string,
  'contentId' : string,
  'text' : string,
  'userPid' : Principal,
  'timestamp' : Time,
}
export interface ContentItem {
  'id' : string,
  'uploaderPid' : Principal,
  'title' : string,
  'contentType' : { 'audio' : null } |
    { 'story' : null },
  'thumbnailBlobId' : [] | [ExternalBlob],
  'createdAt' : Time,
  'authorName' : string,
  'description' : string,
  'genre' : string,
  'blobId' : [] | [ExternalBlob],
  'textContent' : string,
}
export interface ContentItemWithLikes {
  'id' : string,
  'uploaderPid' : Principal,
  'title' : string,
  'likeCount' : number,
  'contentType' : { 'audio' : null } |
    { 'story' : null },
  'thumbnailBlobId' : [] | [ExternalBlob],
  'createdAt' : Time,
  'authorName' : string,
  'description' : string,
  'genre' : string,
  'blobId' : [] | [ExternalBlob],
  'textContent' : string,
}
export type ExternalBlob = Uint8Array;
export interface Progress {
  'contentId' : string,
  'lastAccessed' : Time,
  'position' : number,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookmarkContent' : ActorMethod<[string], undefined>,
  'getAllContent' : ActorMethod<[], Array<ContentItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForContent' : ActorMethod<[string], Array<Comment>>,
  'getContentByType' : ActorMethod<
    [{ 'audio' : null } | { 'story' : null }],
    Array<ContentItem>
  >,
  'getLikeCount' : ActorMethod<[string], [] | [number]>,
  'getProgress' : ActorMethod<[string], [] | [Progress]>,
  'getRecentUploads' : ActorMethod<[], Array<ContentItem>>,
  'getTrendingContent' : ActorMethod<[], Array<ContentItemWithLikes>>,
  'getUserBookmarks' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeContent' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProgress' : ActorMethod<[string, number], undefined>,
  'searchContentByTitle' : ActorMethod<[string], Array<ContentItem>>,
  'unbookmarkContent' : ActorMethod<[string], undefined>,
  'unlikeContent' : ActorMethod<[string], boolean>,
  'uploadContent' : ActorMethod<[ContentItem], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];